### PR TITLE
new feature for combining meshes in 3d hack

### PR DESCRIPTION
**Pull request by aloelazoe**

### CODE REVIEW

**Comment by seleb** [comment]
i'm not sure i'm on board with this one. similar to the drawing replacement, i can see the value in this as a workflow optimization tool, but similarly it's one that could be useful in a normal 2d game too. there'll almost definitely be some changes required in the 3d hack to support combining the two if they were built separate, but i think it's important to try keep things small and digestible (especially in a case like this, where it's a feature that changes how you might accomplish certain things that are already possible, rather than making new things possible).

given the similarity with the drawing replacement hack and the multi-sprite avatar hack, i wonder if all three could be captured by a single hack which more generally added support for grouped/representational sprites?

**Comment by aloelazoe** [comment]
i agree that there are things that you can already do without it only a bit less conveniently like combining meshes/making more layers for static sprites and tiles by adding more rooms to the stack, but with the avatar there is not really a solution, and making 3d hack compatible with multi-sprite avatar would require changing how sprites are handled and accounting for the fact that they can move and making them compatible with smooth moves like the player. it would be nice to do that of course, and perhaps this would also make 3d hack compatible with follower hack, and combining stuff together more easily would be valuable as a standalone hack too, but this would reqiure much more work and i know that i'm not up to it in the near future... i would suggest this children tag more as a temporary solution until a better one is developed. i find it extremely useful and thought that other folks using 3d hack would find it useful too...
re keeping things small, documentation for it took quite a lot of space, i guess it  would make sense to move most of it into the wiki page since it's mostly about details and caveats to keep in mind

**Comment by seleb** [comment]
if this is intended as a temporary solution, it may be better to keep it on a branch and point folks at it as needed. imo the incompatibilities between the 3d hack and others should be treated as bugs, and they should be fixed by addressing the root cause (e.g. removing the assumption in the 3d hack that only the player will move) rather than adding more features that let you work around them

**Comment by aloelazoe** [comment]
i see! makes sense for better organization

**Pull request merged**
