### PR TITLE
feat: add hack math-tool

### PR DESCRIPTION
**Pull request by hundun000**
This hack can use for game logics which need int floor/ceil , example:

- num_can_buy = Math.floor(own_money / price);
- num_battle_turn = Math.ceil(emeny_HP/ player_ATK);

### CODE REVIEW

**Comment by seleb** [comment]
Hey there! Thanks for the contribution, but I have a few concerns about whether this is something that should be merged:

- It seems like you could trivially implement the same behaviour with the existing javascript dialog hack. I'm not sure there's value to a separate hack specifically for exposing the math functions, though I'd be curious to hear if you feel differently. Is there a specific gap this is covering?
- Despite being called "math tools", it's only adding two math functions instead of being a generic interface for `Math`. If you're adding `Math.floor`/`Math.ceil` access, why not `Math.round`, or `Math.trunc`? As someone finding this hack for the first time, I could imagine asking "why doesn't it include X" for pretty much any math function.
- The syntax of these dialog tags is a bit strange. Javascript math functions are generally pure (i.e. they produce certain outputs for given inputs without side effects), but these dialog tags modify a variable by reference. These tags are also built as functions to call separately from other expressions instead of inside them: This means that you cannot combine them to create more complex expressions, and must instead split up your logic across multiple. For example, the single javascript expression:
   ```js
   x = Math.floor(y)
   ```
   would translate to the following, which is two separate expressions:
   ```js
   {x = y}
   {floor "x"}
   ```
    As someone familiar with both languages, I would probably expect it to translate to something like this instead:
   ```js
   {x = {floor y}}
   ```

Let me know if you'd like clarification on any of these points!

**Comment by hundun000** [comment]
Thank you for questions.

- I have tried the js hack. But I found that I don't know how to access the variableMap in the dialog-js excution scope, and maybe it troubles other game developer who only want the simple math operations. Then I found a custom hack function has the environment param which provides GetVariable/SetVariable, so I implemented this hack. Maybe I should ask for more details of the usage of the js hack? 
- Yes. I will try to add more functions. (If this hack still necessary)
- Based on my experience, the Bitsy coding always makes game logic split up. Of course the syntax {x = {floor y}} is better. I found few example about the onReturn so I used default onReturn(null). And I'm not sure what will happend if the hack is inside the built-in operation "=" braces. Is this means I need use onReturn, and the operation "=" will accept the return value?

**Comment by seleb** [comment]
Ah ok, I think some of this is can probably just be solved with improved documentation then: the get/set variable functions are available from global scope too, and I can add an example to the js dialog comments on how to use them. js dialog also currently doesn't use the onReturn and has the same syntax issue as this, so I can make a change to improve that.

Here's an example of what a js dialog version of this would look like with those improvements:
```js
{x = {jsNow "Math.floor(scriptInterpreter.GetVariable('y'))"}
```

It does end up being quite a bit more verbose, so feel free to continue working on this PR to make it generic and more flexible as described and we can merge it, but also feel free to close it if the suggested js dialog improvements are good enough for your use case.

**Comment by seleb** [comment]
ok i pushed up the js dialog improvements: https://github.com/seleb/bitsy-hacks/compare/2efb001397712895b7df2c22f509792405737ce1...e1fa54355575804e8658bddd9e062f61f9d9ed46

lmk if you need any more input!

**Comment by hundun000** [comment]
ok, I decide to use the js hask.

**Pull request closed without merging**
